# Default Settings
title: YulRun.Dev
description: Under Construction
logo: "/assets/images/yulrun_logo_web_dark.png"

# Color scheme supports "light" (default) and "dark"
color_scheme: dark


# External navigation links
nav_external_links:
  - title: Discord
    url: https://discord.gg/bW5pvcdK5j
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false

# External Plugins & Themes
plugins:
  - jekyll-default-layout
  - jekyll-remote-theme
remote_theme: just-the-docs/just-the-docs

